version: "3.11"

services:
  api:
    build: .docker
    container_name: "gemstone_shop_app"
    restart: unless-stopped
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
      - ./storage:/code/storage
    environment:
      - PYTHONPATH=/code
    env_file:
      - .env
