services:
  - type: postgres
    name: gems-postgres
    plan: data
    region: oregon

  - type: web
    name: gemstone-shop-api
    runtime: docker
    repo: https://github.com/jorrgett/gemstone-shop-api.git
    rootDir: .docker
    healthCheckPath: /
    envVars:
      - key: DB_USER
        fromService:
          type: postgres
          name: gems-postgres
          property: user
      - key: DB_PASSWORD
        fromService:
          type: postgres
          name: gems-postgres
          property: password
      - key: DB_HOST
        fromService:
          type: postgres
          name: gems-postgres
          property: host
      - key: DB_NAME
        fromService:
          type: postgres
          name: gems-postgres
          property: database

      - key: MAIL_HOST
        value: smtp.ethereal.email
      - key: MAIL_USERNAME
        value: jorgerafaeltorrestoro@gmail.com
      - key: MAIL_PASSWORD
        value: eevk bxhe turk xuit
      - key: MAIL_PORT
        value: "587"
