services:
  # A Docker web service
  - type: web
    name: gemstone-shop-api
    runtime: image

    image:
      url: docker.io/jorrgett/gemstone-shop-api:2.1.0
    rootDir: app
    healthCheckPath: /
    envVars:
      - key: DB_USER
        value: gems_user
      - key: DB_PASSWORD
        value: trOhcs6W67OARwm1rgyHWzCO2dQvBY1Z
      - key: DB_HOST
        value: dpg-clu784a1hbls73eb0f00-a.oregon-postgres.render.com
      - key: DB_NAME
        value: gems

      - key: MAIL_HOST
        value: smtp.ethereal.email
      - key: MAIL_USERNAME
        value: jorgerafaeltorrestoro@gmail.com
      - key: MAIL_PASSWORD
        value: eevk bxhe turk xuit
      - key: MAIL_PORT
        value: "587"